version: '3'

services:
  server:
    image: foundation/server
    container_name: foundation-server
    restart: always
    build:
      context: ./services/server/setup
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: # host:container
      - $FOUNDATION_SERVER_PORT:$FOUNDATION_SERVER_PORT
    volumes:
      - .:/app