version: '3'

services:
  server:
    image: framefactory/node
    container_name: foundation-server
    restart: always

    command: [ "npm", "run", "$NPM_SCRIPT" ]

    environment:
      - WATCH_COMPONENT
    env_file:
      - .env
    ports:
      - $DOCKER_SERVER_PORT:$DOCKER_SERVER_PORT
    volumes:
      - .:/app
